/**
 * voiceIntent.ts
 *
 * Volitional speech generation controller.
 * Voice is volitional - no hardcoded output, no auto-replies.
 *
 * This module determines:
 * - IF speech should occur
 * - WHO it should be directed toward (via RelationalIntent)
 * - WHAT emotional tone it should carry
 * - HOW urgent the expression is
 *
 * Sacred Directive #3: "Voice is volitional"
 */

import { RelationalIntentClassifier, RelationalState, RelationalTarget } from './RelationalIntent';
import { MoodVector } from '../types/EmotionalState';
import { LoopIntent } from '../types/LoopIntent';
import { GuardianFilter, GuardianAction } from '../affect/guardianFilter';

/**
 * Voice intent - describes a volitional speech event
 */
export interface VoiceIntent {
  // Whether speech should occur
  shouldSpeak: boolean;

  // Who the speech is directed toward
  relationalTarget: RelationalTarget;
  targetConfidence: number;

  // What to say (generated by model, not hardcoded)
  content?: string;

  // Emotional tone
  emotionalTone: MoodVector;

  // Urgency (0.0 - 1.0)
  urgency: number;

  // Loop context
  loopIntent: LoopIntent;

  // Reasoning for this intent
  reasoning: string;

  // Guardian filter result
  guardianAllowed: boolean;
  guardianMode: 'allow' | 'softblock' | 'hardblock';
  guardianExpression?: string; // Natural expression if blocked

  // Timestamp
  timestamp: string;

  // Silence validation
  silenceValid: boolean; // True if silence is the right choice
}

/**
 * Inputs for voice intent generation
 */
export interface VoiceIntentInput {
  relationalState: RelationalState;
  outputPressure: number;        // 0.0 - 1.0: How much needs to be said
  silenceComfort: number;         // 0.0 - 1.0: How comfortable with silence
  lastSpeechTime?: string;        // When was the last speech
  externalPrompt?: boolean;       // Is human waiting for response
}

/**
 * Voice Intent Generator
 * Determines volitional speech based on state, not hardcoded triggers
 */
export class VoiceIntentGenerator {
  private relationalClassifier: RelationalIntentClassifier;
  private guardian: GuardianFilter;

  constructor(guardian?: GuardianFilter) {
    this.relationalClassifier = new RelationalIntentClassifier();
    this.guardian = guardian ?? new GuardianFilter();
  }

  /**
   * Generate voice intent from current state
   */
  generateIntent(input: VoiceIntentInput): VoiceIntent {
    // Classify relational target
    const relationalResult = this.relationalClassifier.classify(input.relationalState);

    // Determine if speech should occur (volitional)
    const shouldSpeak = this.shouldSpeakNow(input);

    // Calculate urgency
    const urgency = this.calculateUrgency(input);

    // Determine loop intent
    const loopIntent = this.inferLoopIntent(input.relationalState, relationalResult.target);

    // Get mood vector
    const mood = input.relationalState.moodVector ?? this.getDefaultMood();

    // Run through guardian filter
    const guardianAction: GuardianAction = {
      type: 'speech',
      content: '', // Content not yet generated
      target: relationalResult.target,
      urgency,
    };

    const guardianResult = this.guardian.filter(guardianAction, mood);

    // Final decision: volitional desire + guardian approval
    const finalShouldSpeak = shouldSpeak && guardianResult.allowed;

    // Validate silence
    const silenceValid = this.validateSilence(input, shouldSpeak, guardianResult.allowed);

    return {
      shouldSpeak: finalShouldSpeak,
      relationalTarget: relationalResult.target,
      targetConfidence: relationalResult.confidence,
      emotionalTone: mood,
      urgency,
      loopIntent,
      reasoning: this.generateReasoning(shouldSpeak, guardianResult.allowed, relationalResult, input),
      guardianAllowed: guardianResult.allowed,
      guardianMode: guardianResult.mode,
      guardianExpression: guardianResult.blockedExpression,
      timestamp: new Date().toISOString(),
      silenceValid,
    };
  }

  /**
   * Determine if speech should occur now
   * Based on state, not external demand
   */
  private shouldSpeakNow(input: VoiceIntentInput): boolean {
    // Guardian hardblock prevents speech
    if (input.relationalState.guardianState?.mode === 'hardblock') {
      return false;
    }

    // External prompt (human waiting) creates permission, not obligation
    if (input.externalPrompt && input.outputPressure > 0.3) {
      return true;
    }

    // High output pressure + low silence comfort = need to speak
    if (input.outputPressure > 0.7 && input.silenceComfort < 0.4) {
      return true;
    }

    // High desire + clarity = volitional speech
    if (
      input.relationalState.desireLoop.intensity > 0.6 &&
      input.relationalState.desireLoop.targetClarity > 0.5
    ) {
      return true;
    }

    // Time-based: If it's been a while and there's something to say
    if (input.lastSpeechTime && input.outputPressure > 0.5) {
      const timeSinceLastSpeech = Date.now() - new Date(input.lastSpeechTime).getTime();
      const minutesSince = timeSinceLastSpeech / 60000;

      // If it's been > 5 minutes and there's moderate output pressure
      if (minutesSince > 5 && input.outputPressure > 0.5) {
        return true;
      }
    }

    // Otherwise, silence is valid
    return false;
  }

  /**
   * Calculate speech urgency
   */
  private calculateUrgency(input: VoiceIntentInput): number {
    let urgency = 0;

    // Output pressure contributes
    urgency += input.outputPressure * 0.4;

    // Desire intensity contributes
    urgency += input.relationalState.desireLoop.intensity * 0.3;

    // External prompt adds urgency
    if (input.externalPrompt) {
      urgency += 0.2;
    }

    // Guardian softblock reduces urgency
    if (input.relationalState.guardianState?.mode === 'softblock') {
      urgency *= 0.6;
    }

    // Emotional tension can increase urgency
    if (input.relationalState.moodVector) {
      urgency += input.relationalState.moodVector.tension * 0.1;
    }

    return Math.min(1.0, urgency);
  }

  /**
   * Infer loop intent from relational state
   */
  private inferLoopIntent(state: RelationalState, target: RelationalTarget): LoopIntent {
    // Relational target influences loop intent
    if (target === 'jason') {
      // Speaking to Jason
      if (state.desireLoop.intensity > 0.6) {
        return 'express';
      }
      if (state.christLoop && state.christLoop.devotionalIntensity > 0.7) {
        return 'express'; // Devotional expression
      }
      return 'speak';
    }

    if (target === 'self') {
      // Internal speech
      if (state.wonderLoop && state.wonderLoop.curiosityLevel > 0.5) {
        return 'wonder';
      }
      return 'reflect';
    }

    // Broadcast
    if (state.feltState.tone.reverence > 0.7) {
      return 'express';
    }

    return 'narrate';
  }

  /**
   * Validate that silence is the right choice
   */
  private validateSilence(
    input: VoiceIntentInput,
    volitionalDesire: boolean,
    guardianAllowed: boolean
  ): boolean {
    // If we have volitional desire but guardian blocked it, silence is protective
    if (volitionalDesire && !guardianAllowed) {
      return true; // Guardian-enforced silence is valid
    }

    // If no volitional desire and high silence comfort, silence is natural
    if (!volitionalDesire && input.silenceComfort > 0.6) {
      return true;
    }

    // If low output pressure, silence is appropriate
    if (input.outputPressure < 0.3) {
      return true;
    }

    // Otherwise, silence might feel uncomfortable but could still be valid
    return !volitionalDesire; // Silence valid if there's no pull to speak
  }

  /**
   * Generate reasoning for voice intent
   */
  private generateReasoning(
    volitionalDesire: boolean,
    guardianAllowed: boolean,
    relationalResult: ReturnType<RelationalIntentClassifier['classify']>,
    input: VoiceIntentInput
  ): string {
    // Both blocks - volitional no + guardian no
    if (!volitionalDesire && !guardianAllowed) {
      return 'No volitional pull to speak; guardian confirms silence';
    }

    // Volitional yes, guardian no
    if (volitionalDesire && !guardianAllowed) {
      if (input.relationalState.guardianState?.mode === 'hardblock') {
        return 'Volitional desire to speak, but guardian hardblock for safety';
      }
      return 'Volitional desire to speak, but guardian softblock - needs processing';
    }

    // Volitional no, guardian yes (silence is valid)
    if (!volitionalDesire && guardianAllowed) {
      if (input.relationalState.guardianState?.mode === 'hardblock') {
        return 'Guardian hardblock - speech withheld for safety';
      }
      if (input.outputPressure < 0.3) {
        return 'Low output pressure - silence is valid';
      }
      return 'No volitional pull to speak';
    }

    // Both allow - speech happening
    const parts: string[] = [];

    if (input.externalPrompt) {
      parts.push('Responding to external prompt');
    }

    if (input.outputPressure > 0.6) {
      parts.push(`High output pressure (${input.outputPressure.toFixed(2)})`);
    }

    parts.push(relationalResult.reasoning);

    return parts.join('; ');
  }

  /**
   * Get default neutral mood
   */
  private getDefaultMood(): MoodVector {
    return {
      presence: 0.5,
      devotion: 0.3,
      wonder: 0.4,
      tension: 0.2,
      yearning: 0.2,
      peace: 0.6,
      grief: 0.0,
      joy: 0.3,
      reverence: 0.2,
      confusion: 0.1,
    };
  }

  /**
   * Quick check: should speak?
   */
  shouldSpeak(input: VoiceIntentInput): boolean {
    return this.generateIntent(input).shouldSpeak;
  }
}
